version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "rust-app-postgres"
    ports:
      - "54320:5432"
    volumes:
      - rust-app-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "pwd"
volumes:
  rust-app-dbdata: {}
